unbind C-b
set -g prefix `
bind ` last-window
bind e send-prefix

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

setw -g mouse on
# setw -g mode-keys vi

set -g status-position bottom

set -g status-bg colour235
set -g status-fg colour208

set -g status-left ''

set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,none] %H:%M '

setw -g window-status-current-format '#[bg=colour238] #I#[fg=colour250]:#[fg=colour255]#{b:pane_current_path}#[fg=colour244][#W]#[fg=colour50]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#{b:pane_current_path}#[fg=colour244][#W]'

set-option -g renumber-windows on

bind -r y run-shell '\
    SESSION="codex-$(printf "%s" "#(pane_current_path) | md5 -q | cut -c1-8)"; \
    tmux has-session -t "$SESSION" 2>/dev/null || \
    tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "codex"; \
    tmux display-popup -d "#{pane_current_path}" -w80% -h80% -E "tmux attach-session -t $SESSION"'
